# Generated by Django 5.0 on 2024-01-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('package_type', models.CharField(max_length=16)),
                ('discount_code', models.IntegerField(null=True)),
                ('number_of_exchange', models.IntegerField()),
                ('number_of_currencies', models.IntegerField()),
                ('number_of_position_for_each_exchange_in_month', models.IntegerField()),
                ('number_of_create_strategy', models.IntegerField()),
                ('can_use_timeout', models.BooleanField()),
                ('can_access_to_zone', models.BooleanField()),
                ('can_access_to_spread', models.BooleanField(null=True)),
                ('can_access_to_allow_price', models.BooleanField()),
                ('trade_history', models.BooleanField()),
                ('can_use_stop_loss', models.BooleanField()),
                ('can_use_profit', models.BooleanField()),
                ('can_check_position_on_chart', models.BooleanField()),
                ('get_notifications', models.CharField(max_length=16)),
                ('can_download_result', models.BooleanField(null=True)),
                ('professional_report', models.CharField(max_length=32, null=True)),
                ('open_position', models.IntegerField()),
                ('start_data', models.DateField(auto_now_add=True)),
                ('period_validity', models.IntegerField()),
            ],
        ),
    ]
