# Generated by Django 5.0 on 2024-01-31 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='trade_history',
        ),
        migrations.AddField(
            model_name='package',
            name='automate_manual',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='can_view_trade_history',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='num_of_scan_for_each_exchange_per_day',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='number_of_coins_for_signals',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='number_of_sig_for_each_day',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='can_access_to_allow_price',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='can_access_to_zone',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='can_check_position_on_chart',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='can_use_profit',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='can_use_stop_loss',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='can_use_timeout',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='number_of_create_strategy',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='number_of_currencies',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='number_of_exchange',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='number_of_position_for_each_exchange_in_month',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='open_position',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='period_validity',
            field=models.IntegerField(null=True),
        ),
    ]
