# Generated by Django 5.0 on 2024-03-12 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='users',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='users',
            name='card',
        ),
        migrations.RemoveField(
            model_name='users',
            name='city',
        ),
        migrations.RemoveField(
            model_name='users',
            name='country',
        ),
        migrations.RemoveField(
            model_name='users',
            name='passport_number',
        ),
        migrations.RemoveField(
            model_name='users',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='users',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='users',
            name='secret_question',
        ),
        migrations.AddField(
            model_name='users',
            name='referral_code',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=16, null=True, unique=True)),
                ('passport_number', models.ImageField(null=True, upload_to='passport_number')),
                ('self_photo', models.ImageField(null=True, upload_to='self_photo')),
                ('birthday', models.DateField(null=True)),
                ('country', models.CharField(max_length=32, null=True)),
                ('city', models.CharField(max_length=32, null=True)),
                ('secret_question', models.TextField(null=True)),
                ('answer', models.TextField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(default='signal', max_length=16)),
                ('telegram_id', models.CharField(max_length=32)),
                ('time_for_signal', models.CharField(max_length=128)),
                ('favorite_asset_names', models.TextField()),
                ('exchange_names', models.TextField()),
                ('favorite_time_frames', models.TextField()),
                ('rules', models.TextField()),
                ('wallet_amount', models.FloatField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
