# Generated by Django 5.0 on 2024-03-13 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_users_referral_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(default='hire', max_length=16)),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('job_title', models.CharField(max_length=64)),
                ('country', models.CharField(max_length=32)),
                ('city', models.CharField(max_length=32)),
                ('cv', models.FileField(upload_to='cv')),
                ('descriptions', models.TextField()),
                ('passport_number', models.ImageField(upload_to='passport_number')),
                ('self_photo', models.ImageField(upload_to='self_photo')),
            ],
        ),
        migrations.RemoveField(
            model_name='support',
            name='user',
        ),
    ]
