# Generated by Django 5.0 on 2024-03-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_hire_remove_support_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hire',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='hire',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='support',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='support',
            name='name',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
