# Generated by Django 5.0 on 2024-03-16 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_hire_email_alter_hire_name_alter_support_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hire',
        ),
        migrations.RemoveField(
            model_name='signal',
            name='user',
        ),
        migrations.DeleteModel(
            name='Support',
        ),
        migrations.DeleteModel(
            name='Signal',
        ),
    ]
