# Generated by Django 5.0 on 2024-02-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='description',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
