# Generated by Django 5.0 on 2024-03-09 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_news_image_news_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
