# Generated by Django 5.0 on 2024-03-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='object_type',
            field=models.CharField(max_length=16),
        ),
    ]
