# Generated by Django 5.0 on 2024-02-06 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MACD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ema12', models.FloatField()),
                ('ema26', models.FloatField()),
                ('signal', models.FloatField()),
                ('macd_cross_signal', models.IntegerField()),
                ('macd_cross_zero', models.IntegerField()),
                ('signal_cross_zero', models.IntegerField()),
                ('consider', models.IntegerField()),
                ('candle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='export.candle')),
            ],
        ),
        migrations.CreateModel(
            name='Stochastic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('k', models.FloatField(null=True)),
                ('d', models.FloatField(null=True)),
                ('candle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='export.candle')),
            ],
        ),
    ]
