# Generated by Django 5.0 on 2024-02-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0002_candle_macd_stochastic'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('ema12', models.FloatField()),
                ('ema26', models.FloatField()),
                ('macd', models.FloatField()),
                ('signal', models.FloatField()),
                ('macd_cross_signal', models.IntegerField()),
                ('macd_cross_zero', models.IntegerField()),
                ('signal_cross_zero', models.IntegerField()),
                ('consider', models.IntegerField()),
                ('%k', models.FloatField(null=True)),
                ('%D', models.FloatField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='stochastic',
            name='candle',
        ),
        migrations.DeleteModel(
            name='MACD',
        ),
        migrations.DeleteModel(
            name='Candle',
        ),
        migrations.DeleteModel(
            name='Stochastic',
        ),
    ]
