# Generated by Django 5.0 on 2024-01-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_name', models.CharField(max_length=16)),
                ('account_name', models.CharField(max_length=32)),
                ('api_key', models.CharField(max_length=128, null=True)),
                ('secret_key', models.CharField(max_length=128, null=True)),
                ('max_allow_position', models.IntegerField()),
            ],
        ),
    ]
