# Generated by Django 5.0 on 2024-01-30 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exchange',
            unique_together=set(),
        ),
    ]
