# Generated by Django 5.0 on 2024-02-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0003_alter_exchange_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchange',
            name='max_allow_position',
        ),
        migrations.AddField(
            model_name='exchange',
            name='ip_address',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
