# Generated by Django 5.0 on 2024-01-29 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='indicator',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='indicator.indicator'),
        ),
    ]
