# Generated by Django 5.0 on 2024-01-29 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('indicator', '0001_initial'),
        ('strategy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='close_str',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='close', to='strategy.strategy'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='open_str',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='open', to='strategy.strategy'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='settings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='indicator.setting'),
        ),
    ]
