# Generated by Django 5.0 on 2024-02-07 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicator',
            name='buy_sell',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='keep_signal',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='necessary',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='time_frame',
        ),
        migrations.AddField(
            model_name='setting',
            name='buy_sell',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='d_smoothing',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='k_length',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='k_smoothing',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='keep_signal',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='ma_length',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='ma_size',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='ma_type',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='necessary',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='time_frame',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='setting',
            name='indicator',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='indicator.indicator'),
        ),
    ]
