# Generated by Django 5.0 on 2024-02-10 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0002_remove_indicator_buy_sell_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='rsi_length',
        ),
    ]
