# Generated by Django 5.0 on 2024-01-31 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0002_alter_setting_indicator'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='cross_macd_zero',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='cross_mcd_zero',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='cross_sig_zero',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='ma_length',
            field=models.IntegerField(null=True),
        ),
    ]
