# Generated by Django 5.0 on 2024-02-16 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0003_remove_setting_rsi_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='rsi_type',
        ),
    ]
