# Generated by Django 5.0 on 2024-01-31 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0003_setting_cross_macd_zero_setting_cross_mcd_zero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='cross_k_d',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='cross_k_lower',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='cross_k_upper',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='d_smoothing',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='k_length',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='k_smoothing',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='ma_size',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='ma_type',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
