# Generated by Django 5.0 on 2024-02-22 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0004_remove_setting_rsi_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='OHLCV_value',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='consider',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='cross',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='d_smoothing',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='fast_period',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='k_length',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='k_smoothing',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='long_period',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='lower_band',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='ma_length',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='ma_size',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='ma_type',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='short_period',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='signal_period',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='slow_period',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='upper_band',
        ),
        migrations.AlterField(
            model_name='setting',
            name='buy_sell',
            field=models.CharField(default=' both', max_length=16),
        ),
        migrations.AlterField(
            model_name='setting',
            name='keep_signal',
            field=models.CharField(default='0', max_length=16),
        ),
        migrations.AlterField(
            model_name='setting',
            name='necessary',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='time_frame',
            field=models.CharField(default='4h', max_length=8),
        ),
        migrations.CreateModel(
            name='MACD',
            fields=[
                ('setting_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='indicator.setting')),
                ('OHLCV_value', models.CharField(default='close', max_length=128)),
                ('fast_length', models.IntegerField(default=12)),
                ('slow_length', models.IntegerField(default=26)),
                ('signal_smoothing', models.IntegerField(default=9)),
                ('cross', models.CharField(default='', max_length=128)),
                ('consider', models.BooleanField(default=False)),
            ],
            bases=('indicator.setting',),
        ),
    ]
