# Generated by Django 5.0 on 2024-02-06 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0004_setting_cross_k_d_setting_cross_k_lower_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='cross_k_d',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='cross_k_lower',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='cross_k_upper',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='cross_macd_zero',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='cross_mcd_zero',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='cross_sig_zero',
        ),
    ]
