# Generated by Django 5.0 on 2024-02-22 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('indicator', '0005_remove_setting_ohlcv_value_remove_setting_consider_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='macd',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='setting',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='setting',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
    ]
