# Generated by Django 5.0 on 2024-02-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0006_alter_macd_options_alter_setting_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macd',
            name='consider',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='macd',
            name='cross',
            field=models.CharField(default='', max_length=128, null=True),
        ),
    ]
