# Generated by Django 5.0 on 2024-02-27 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0008_ma_obv_rsi_rsicross_rsima_std_stochastic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='macd',
            old_name='OHLCV_value',
            new_name='ohlcv_value',
        ),
    ]
