# Generated by Django 5.0 on 2024-02-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0009_rename_ohlcv_value_macd_ohlcv_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rsicross',
            old_name='signal_upper_grater',
            new_name='signal_upper_greater',
        ),
        migrations.AlterField(
            model_name='stochastic',
            name='for_buy_lower',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='stochastic',
            name='for_buy_lower_upper',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='stochastic',
            name='for_sell_lower_upper',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='stochastic',
            name='for_sell_upper',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
