# Generated by Django 5.0 on 2024-02-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0010_rename_signal_upper_grater_rsicross_signal_upper_greater_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stochastic',
            name='for_buy_lower',
            field=models.CharField(default='', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='stochastic',
            name='for_buy_lower_upper',
            field=models.CharField(default='', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='stochastic',
            name='for_sell_lower_upper',
            field=models.CharField(default='', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='stochastic',
            name='for_sell_upper',
            field=models.CharField(default='', max_length=128, null=True),
        ),
    ]
