# Generated by Django 5.0 on 2024-01-29 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot', '0001_initial'),
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='exchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.exchange'),
        ),
    ]
