# Generated by Django 5.0 on 2024-02-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='trade_market',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
