# Generated by Django 5.0 on 2024-03-09 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_rename_exchanges_id_bot_market_accounts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='asset_name',
        ),
        migrations.AddField(
            model_name='asset',
            name='bot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='asset_name', to='bot.bot'),
            preserve_default=False,
        ),
    ]
