# Generated by Django 5.0 on 2024-03-09 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_remove_bot_asset_name_asset_bot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='bot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_name', to='bot.bot'),
        ),
    ]
