# Generated by Django 5.0 on 2024-03-16 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_bot_user'),
        ('strategy', '0004_strategy_low_high_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='strategy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bots', to='strategy.strategy'),
        ),
    ]
